default_install_hook_types:
  - pre-commit
  - commit-msg

repos:
  - repo: https://github.com/crate-ci/typos
    rev: v1.45.2
    hooks:
      - id: typos
        name: Check typos for files
        stages: [pre-commit]
      - id: typos
        name: Check typos for commit messages
        stages: [commit-msg]

  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.4.0
    hooks:
      - id: conventional-pre-commit
        stages: [commit-msg]
        args: [--verbose]

  - repo: local
    hooks:
      - id: build-module
        name: Build module
        entry: pwsh -NoProfile -ExecutionPolicy Bypass -File build.ps1
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
